// Generated by LiveScript 1.3.1
var express, redis, client, app, PORT;
express = require('express');
redis = require('redis');
client = redis.createClient();
client.on('error', function(it){
  return console.log(it);
});
app = express();
PORT = process.env.PORT || 8080;
app.get('/:id', function(req, res){
  var id;
  if (req.params.id) {
    id = req.params.id;
    return client.get(id, function(err, reply){
      if (id.match(/json$/)) {
        reply = JSON.parse(reply);
      }
      return res.json({
        data: reply
      });
    });
  } else {
    return res.json('KAGE API');
  }
});
app.listen(PORT, function(){
  return console.log("server listen on " + PORT);
});