// Generated by LiveScript 1.3.1
var express, redis, dump, ref$, REDIS_IP, REDIS_PORT, PORT, ref1$, client, app;
express = require('express');
redis = require('redis');
dump = require('./dump');
ref$ = process.env, REDIS_IP = ref$.REDIS_IP, REDIS_PORT = ref$.REDIS_PORT, PORT = (ref1$ = ref$.PORT) != null ? ref1$ : 8080;
console.log("connect to " + REDIS_IP + ":" + REDIS_PORT);
client = redis.createClient(+REDIS_PORT, REDIS_IP);
client.on('error', function(it){
  return console.log(it);
});
app = express();
app.get('/:id', function(req, res){
  var id;
  if (req.params.id) {
    id = req.params.id;
    return client.get(id, function(err, reply){
      if (id.match(/\.json$/)) {
        return res.json(JSON.parse(reply));
      } else {
        return res.send(reply);
      }
    });
  } else {
    return res.json('KAGE API');
  }
}).put('/dump', function(req, res){
  return dump(function(entryCount){
    return res.json({
      entryUpdated: entryCount
    });
  });
});
app.listen(PORT, function(){
  return console.log("server listen on " + PORT);
});